spring:
  application:
    name: flight-search
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true


app:
  jwt:
    secret: a88ddc9d796717bd0aab13d65e0f46cbf6c84c3a7a513a30d2c27e1b5f3431d7
